import { Inter as FontSans } from "next/font/google";

import { Layout } from "@/components/ui/layout";

import { cn } from "@/lib/utils";
import "@/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "overscroll-none whitespace-pre-line bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
